spring:
  cloud:
    gateway:

#      globalcors:
#        add-to-simple-url-handler-mapping: true   # ← important for OPTIONS
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins:
#              - "http://localhost:5173"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - PATCH
#              - OPTIONS
#            allowedHeaders: "*"
#            exposedHeaders:
#              - Authorization
#              - Content-Type
#              - X-User-Email
#              - X-Role
#            allowCredentials: true
#            maxAge: 3600

      server:
        webflux:
          routes:
#            - id: preflight-handler
#              uri: no://op   # dummy URI — not used
#              order: -1000   # highest priority — runs first
#              predicates:
#                - Method=OPTIONS
#              filters:
#                - AddResponseHeader=Access-Control-Allow-Origin, http://localhost:5173
#                - AddResponseHeader=Access-Control-Allow-Methods, "GET,POST,PUT,DELETE,PATCH,OPTIONS"
#                - AddResponseHeader=Access-Control-Allow-Headers, "*"
#                - AddResponseHeader=Access-Control-Allow-Credentials, true
#                - AddResponseHeader=Access-Control-Max-Age, 3600
#                - RewritePath=/.+, /dummy   # dummy rewrite (not needed)

            - id: food-service
              uri: lb://food-service
              predicates:
                - Path=/api/foods/**

            - id: authentication-service
              uri: lb://authentication-service
              predicates:
                - Path=/api/auth/**

            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/api/cart/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/order/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payment/**
            - id: contact-service
              uri: lb://contact-service
              predicates:
                - Path=/api/contactUs/**
      discovery:
        locator:
          lower-case-service-id: true




management:
  endpoints:
    web:
      exposure:
        include: gateway

jwt:
  secret:
    key: ${JWT_SECRET_KEY:498502c0fe7d53807379353f7cb75de227f635981762319b39a2aab6cf92a995}


logging:
  level:
    org.springframework.cloud.gateway: TRACE