spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: food-service
              uri: lb://food-service
              predicates:
                - Path=/api/foods/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: foodServiceCircuit
                    fallbackUri: forward:/fallback/foodService

                - name: Retry
                  args:
                    retries: 3
                    statuses:
                      - BAD_GATEWAY
                      - INTERNAL_SERVER_ERROR
                    methods: GET
                    backoff:
                      firstBackoff: 500ms
                      maxBackoff: 2s
                      factor: 2

            - id: authentication-service
              uri: lb://authentication-service
              predicates:
                - Path=/api/auth/**

            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=/api/cart/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/order/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payment/**
            - id: contact-service
              uri: lb://contact-service
              predicates:
                - Path=/api/contactUs/**
      discovery:
        locator:
          lower-case-service-id: true


resilience4j:
  circuitbreaker:
    instances:
      foodServiceCircuit:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret:
    key: ${JWT_SECRET_KEY:498502c0fe7d53807379353f7cb75de227f635981762319b39a2aab6cf92a995}


logging:
  level:
    org.springframework.cloud.gateway: TRACE